/* Generated By:JavaCC: Do not edit this line. TPTPConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TPTPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 1;
  /** RegularExpression Id. */
  int BECOMES = 2;
  /** RegularExpression Id. */
  int ELSE = 3;
  /** RegularExpression Id. */
  int AND = 4;
  /** RegularExpression Id. */
  int RUN = 5;
  /** RegularExpression Id. */
  int COLON = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int LPAREN = 8;
  /** RegularExpression Id. */
  int RPAREN = 9;
  /** RegularExpression Id. */
  int LESS_THAN = 10;
  /** RegularExpression Id. */
  int SEMICOLON = 11;
  /** RegularExpression Id. */
  int NUM = 12;
  /** RegularExpression Id. */
  int ID = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"if\"",
    "\"becomes\"",
    "\"else\"",
    "\"and\"",
    "\"run\"",
    "\":\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\";\"",
    "<NUM>",
    "<ID>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
  };

}
